# Paths
music_directory     "~/.local/share/mpd/music"
playlist_directory  "~/.local/share/mpd/playlists"
db_file             "~/.cache/mpd/database"
log_file            "~/.cache/mpd/log"
pid_file            "~/.cache/mpd/pid"
state_file          "~/.cache/mpd/state"
sticker_file        "~/.cache/mpd/sticker.sql"

# Network
bind_to_address     "127.0.0.1"
port                "6600"

# Audio output
audio_output {
    type    "pipewire"
    name    "PipeWire Output"
}

# Ignore wildmidi warning
decoder {
    plugin "wildmidi"
    enabled "no"
}

# General
restore_paused      "yes"
auto_update         "yes"
