[[session]]
name = "󱂵 home"
path = "~"
startup_command = 'yupdate'

[[session]]
name = " drive"
path = "~/Documents/drive"

[[session]]
name = " downloads"
path = "~/Downloads"

[[session]]
name = " pictures"
path = "~/Pictures"

[[session]]
name = " dotfiles"
path = "~/dotfiles"
startup_command = 'nvim'

[[session]]
name = " workspace"
path = "~/w"

[[session]]
name = " nvim"
path = "~/.config/nvim"
startup_command = 'nvim'

[[session]]
name = " second brain"
path = "~/w/2-areas/second-brain.md"
startup_command = 'make'

[[session]]
name = "  music"
path = "~/Music"
startup_command = 'make'

[[session]]
name = "󰂾 library"
path = "~/library"
startup_command = 'zathura'

[[session]]
name = "  english"
path = "~/Documents/english/passive-audio"
startup_command = 'play'

[[session]]
name = " chadwm"
path = "~/.config/chadwm"

[[session]]
name = "󰊠 ghostty"
path = "~/.config/ghostty"
startup_command = 'nvim config'

[[session]]
name = " sesh"
path = "~/.config/sesh"
startup_command = 'nvim sesh.toml'

[[session]]
name = " emacs"
path = "~/.config/emacs"

[[session]]
name = "󰆍 wezterm"
path = "~/.config/wezterm"
startup_command = 'nvim wezterm.lua'

[[session]]
name = "󰣉 projects"
path = "~/w/1-projects"

[[session]]
name = " areas"
path = "~/w/2-areas"

[[session]]
name = "󱉏 resources"
path = "~/w/3-resources"

[[session]]
name = " archives"
path = "~/w/4-archives"
