[[session]]
name = "󱂵 home"
path = "~"

[[session]]
name = "󰚌 work"
path = "~/workspace/work"

[[session]]
name = "󰏃 entities"
path = "~/workspace/work/entities/"

[[session]]
name = "󰏃 users"
path = "~/workspace/work/users"

[[session]]
name = "󰏃 management"
path = "~/workspace/work/management"

[[session]]
name = " drive"
path = "~/Documents/drive"

[[session]]
name = " downloads"
path = "~/Downloads"

[[session]]
name = " pictures"
path = "~/Pictures"

[[session]]
name = "󰏃 services"
path = "~/workspace/work/services"

[[session]]
name = "󰏃 payments"
path = "~/workspace/work/payments"

[[session]]
name = "󰏃 dashboard"
path = "~/workspace/work/dashboard"

[[session]]
name = "󰏃 operator-app"
path = "~/workspace/work/operator-app"

[[session]]
name = " deploy"
path = "~/workspace/work/deploy"

[[session]]
name = " dotfiles"
path = "~/dotfiles"

[[session]]
name = " workspace"
path = "~/workspace"

[[session]]
name = " nvim"
path = "~/.config/nvim"

[[session]]
name = " second brain"
path = "~/Documents/second-brain.md"

[[session]]
name = "󱎫 multi-timer"
path = "~/workspace/multi-timer"
