[[session]]
name = "󱂵 home"
path = "~"

[[session]]
name = " drive"
path = "~/Documents/drive"

[[session]]
name = " downloads"
path = "~/Downloads"

[[session]]
name = " pictures"
path = "~/Pictures"

[[session]]
name = " dotfiles"
path = "~/dotfiles"

[[session]]
name = " workspace"
path = "~/w"

[[session]]
name = " nvim"
path = "~/.config/nvim"

[[session]]
name = " second brain"
path = "~/w/2-areas/second-brain.md"
startup_command = 'n-start-second-brain-tmux-session'

[[session]]
name = "  music"
path = "~/Music"
startup_command = 'play'

[[session]]
name = "󰂾 library"
path = "~/library"
startup_command = 'zathura'

[[session]]
name = "  english"
path = "~/Documents/english/passive-audio"
startup_command = 'play'

[[session]]
name = " chadwm"
path = "~/.config/chadwm"

[[session]]
name = "󰊠 ghostty"
path = "~/.config/ghostty"
startup_command = 'nvim config'

[[session]]
name = " emacs"
path = "~/.config/emacs"

[[session]]
name = "󰆍 wezterm"
path = "~/.config/wezterm"
startup_command = 'nvim wezterm.lua'
