[[session]]
name = "󱂵 home"
path = "~"

[[session]]
name = " downloads"
path = "~/Downloads"

[[session]]
name = " pictures"
path = "~/Pictures"

[[session]]
name = " dotfiles"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = " workspace"
path = "~/w"

[[session]]
name = " nvim"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = " second brain"
path = "~/w/a/second-brain.md/src"
startup_command = "nvim"

[[session]]
name = "󰯊 notes"
path = "~/w/a/second-brain.md/src"

[[session]]
name = " music"
path = "~/Music"
startup_command = "just"

[[session]]
name = " dwm"
path = "~/.config/dwm"
startup_command = "nvim config.def.h"

[[session]]
name = "󰊠 ghostty"
path = "~/.config/ghostty"
startup_command = "nvim config"

[[session]]
name = " sesh"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = " emacs"
path = "~/.config/emacs"

[[session]]
name = "󰆍 wezterm"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "󰣉 projects"
path = "~/w/p"

[[session]]
name = " areas"
path = "~/w/a"

[[session]]
name = "󰐀 Pi"
path = "~/dotfiles/pi-agent/.pi/agent/"

[[session]]
name = " Bob"
path = "/home/nikola/.local/share/bob/nightly/share/nvim/runtime"
