scan_timeout = 60

[character]
vimcmd_symbol = '[](bold green)'

[cmd_duration]
format = "[$duration]($style) "

[git_metrics]
added_style = 'green'
deleted_style = 'red'
disabled = false
format = "([ $added]($added_style) )([ $deleted]($deleted_style) )"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "

[git_status]
ahead = "[ ${count} ](yellow)"
behind = "[ ${count} ](yellow)"
conflicted = "[ ${count} ](red)"
deleted = "[ ${count} ](red)"
diverged = "[󰔪 ${count} ](red)"
format = "[| $all_status$ahead_behind]($style)"
modified = "[ ${count} ](blue)"
renamed = "[ ${count} ](blue)"
staged = "[ ${count} ](green)"
stashed = "[ ${count} ](cyan)"
style = 'black'
untracked = "[ ${count} ](white)"

[status]
disabled = false
format = "[$symbol $status]($style) "
map_symbol = true
not_executable_symbol = " "
not_found_symbol = " "
sigint_symbol = " "
symbol = " "

[golang]
format = '[$symbol($version )($mod_version )]($style)'
symbol = " "

[package]
format = "[$symbol$version]($style) "
symbol = "󰏖 "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "󰋘 "

[lua]
format = "[$symbol($version )]($style)"
style = "#42a5f5"
symbol = " "

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = " "
