#!/bin/dash

# ---------------------------------------------- Colors ---------------------------------------------- #

black=#222526
blue=#6f8faf
darkblue=#6080a0
green=#89b482
grey=#2b2e2f
red=#ec6b64
white=#c7b89d
