#!/bin/dash

# ---------------------------------------------- Colors ---------------------------------------------- #

black=#2e3440
blue=#81a1c1
darkblue=#7292b2
green=#a3be8c
grey=#373d49
red=#bf616a
white=#d8dee9
