#!/usr/bin/env bash

function main() {
  commands=$(fd "^n-*" $HOME/.local/bin --exec basename)

  choice=$(printf '%s\n' "${commands[@]}" | sort | rofi -dmenu -i -p "󰘳 Commands ")
  if [[ ! -n "$choice" ]]; then
    return
  fi

  eval "$choice"
}

main
