#!/usr/bin/env bash

function main {
    local script=$(jq -r '.scripts | keys[]' package.json | fzf --height=10 --prompt="   ")

    if [[ -e bun.lockb ]]; then
        bun run $script
    elif [[ -e bun.lock ]]; then
        bun run $script
    elif [[ -e yarn.lock ]]; then
        yarn run $script
    elif [[ -e package-lock.json ]]; then
        npm run $script
    else
        echo "Package manager is not recorgnized"
        exit 1
    fi
}

main
