#!/usr/bin/env python

import sys

def array_includes(array, element):
    array_includes_ = False
    for x in array:
        if x == element:
            array_includes_ = True
            break

    return array_includes_


def extract_first_letters_with_puntuation(line):
    result = ""

    line_divide_in_spaces = line.split(" ")


    for word in line_divide_in_spaces:
        if word.strip() == '':
            continue

        if "'" in word:
            result += word + " "
            continue

        first_character = word[0]
        last_index = len(word) - 1
        last_character = word[last_index]

        result += first_character

        if array_includes([",", ".", "!"], last_character):
            result += last_character

        result += " "

    return result


def get_words(text):
    result = ""
    lines = text.split('\n')


    for line in lines:
        if line.strip() == '':
            continue

        result += extract_first_letters_with_puntuation(line).strip() + "\n"

    print(result, end = '')


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python uppercase.py <sentence>")
        sys.exit(1)

    sentence = sys.argv[1]
    get_words(sentence)
