#!/usr/bin/env bash

_sesh_list_sk() {
  sesh list -i | sk --tmux \
    --ansi \
    --reverse \
    --bind 'ctrl-a:change-prompt(  )+reload(sesh list -i)' \
    --bind 'ctrl-c:change-prompt(  )+reload(sesh list -ic)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(  )+reload(sesh list -t)' \
    --bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-t:change-prompt(  )+reload(sesh list -it)' \
    --bind 'ctrl-x:change-prompt(  )+reload(sesh list -iz)' \
    --selector '' \
    --prompt "  Sesh List   " \
    --multi-selector '▎' \
    --header '[ ^-a all  ^t tmux  ^x zoxide  ^c config  ^d tmux kill  ^f find ]' \
    --no-sort
}

_sesh_list_fzf() {
  sesh list -i | fzf-tmux -p 40%,30% \
    --ansi \
    --reverse \
    --bind 'ctrl-a:change-prompt(  )+reload(sesh list -i)' \
    --bind 'ctrl-c:change-prompt(  )+reload(sesh list -ic)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(  )+reload(sesh list -t)' \
    --bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-t:change-prompt(  )+reload(sesh list -it)' \
    --bind 'ctrl-x:change-prompt(  )+reload(sesh list -iz)' \
    --border-label '  󰍒 Sesh List  ' \
    --header '[ ^-a all  ^t tmux  ^x zoxide  ^c config  ^d tmux kill  ^f find ]' \
    --no-sort
}

_sesh_list() {
  _sesh_list_sk
}

function main() {
  sesh connect "$(_sesh_list)"
}

main
