#!/usr/bin/env bash

# Configs
alias A="cd ~/.config/alacritty && nvim alacritty.toml"
alias C="cd ~/.config"
alias csessions="gio trash ~/.local/share/nvim/sessions/"
alias dbnvim="rm -rf ~/.local/share/nvim && rm -rf ~/.cache/nvim/lazy"
alias dc="cd ~/Documents"
alias D="cd ~/dotfiles && nvim"
alias dl="cd ~/Downloads"
alias g="cd ~/Documents/drive"
alias G="cd ~/go/src/github.com/NikolaM-Dev"
alias grub-cfg="sudo nvim /etc/default/grub"
alias lb="cd ~/library"
alias ncache="rm -rf ~/.cache/nvim/lazy"
alias pacman-cfg="sudo nvim /etc/pacman.conf"
alias P="cd ~/Pictures"
alias R="cd ~/workspace/react"
alias sb="cd ~/Documents/second-brain.md && nvim"
alias ss="sudo -E -s"
alias V="cd ~/.config/nvim && nvim"
alias W="cd ~/workspace"
alias year='cal -mwy'
alias zc="nvim ~/.zshrc"

# Pacman
alias padd="sudo pacman -S"
alias pfind="sudo pacman -Ss"
alias prm="sudo pacman -Rsun"
alias pupdate="sudo pacman -Syu && yay -Syu && omz update"

# Yay
alias yadd="yay -S"
alias yfind="yay -Ss"
alias ysc="yay -Sc"

# Crud
alias ...="cd ../.."
alias ..="cd .."
alias ctrash="gio trash --empty"
alias gt="gio trash"
alias rmf="rm -rf"
alias to="touch"
alias trash="cd ~/.local/share/Trash/files"

# Git
alias ga="git add --all"
alias gb="git branch"
alias gca="git commit --amend"
alias gcanedit="git commit --amend --no-edit"
alias gc="git commit -m"
alias gct="git checkout"
alias gfa="git fetch --all -p -P"
alias gfresh="git reset --hard HEAD && git clean -f -d"
alias gi="git init"
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
alias gma="git merge --abort"
alias gmfbc="git pull origin --no-edit qa && gp"
alias gmfdev="git merge --no-ff --no-edit develop && gp"
alias gmfmain="git merge --no-ff --no-edit qa && gp"
alias gmfqa="git merge --no-ff --no-edit qa && gp"
alias gm="git merge --no-ff --no-edit"
alias gp="git push"
alias gpl="git pull"
alias gpof="git push origin -f HEAD"
alias gpo="git push origin -u HEAD"
alias gpt="git push --tags"
alias grank="git shortlog -sn --no-merges"
alias gr="git remote"
alias gs="git status -sb"
alias gsl="git stash list"
alias gst="git stash -um"
alias gsw="git switch"
alias gta="git tag -a"
alias gtl="git tag -l"

# yarn
alias yad="yarn add -D -E"
alias ya="yarn add -E"
alias yi="npm init -y"
alias yrm="yarn remove"

# Golang
alias gcoverage="go test -coverprofile=coverage.out; go tool cover -o coverage.html -html=coverage.out; google-chrome-stable coverage.html"
alias gdtelemetry="go run golang.org/x/telemetry/cmd/gotelemetry@latest off"
alias gmi="go mod init"
