scan_timeout = 60

[cmd_duration]
format = "[$duration]($style) "

[git_metrics]
format = "([ $added]($added_style) )([ $deleted]($deleted_style) )"
disabled = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "

[status]
disabled = false
format = "[$symbol $status]($style) "
map_symbol = true
not_executable_symbol = " "
not_found_symbol = " "
sigint_symbol = " "
symbol = " "

[golang]
format = '[$symbol($version )($mod_version )]($style)'
symbol = " "

[package]
format = "[$symbol$version]($style) "
symbol = "󰏖 "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "󰋘 "

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = " "
