#!/bin/dash

# ---------------------------------------------- Colors ---------------------------------------------- #

black=#1e222a
blue=#7aa2f7
darkblue=#668ee3
green=#7eca9c
grey=#282c34
red=#d47d85
white=#abb2bf
