#!/usr/bin/env bash

# ---------------------------------------------- Colors ---------------------------------------------- #

love=#eb6f92
gold=#f6c177
iris=#c4a7e7
foam=#9ccfd8
rose=#ea9a97
leaf=#95b1ac
pine=#3e8fb0
