adjust-cell-width = -5%
font-family = Aporetic Sans Mono
font-family-bold = Aporetic Sans Mono
font-family-bold-italic = Aporetic Sans Mono
font-family-italic = Aporetic Sans Mono
font-family = Symbols Nerd Font
font-size = 14

# vim: commentstring=#\ %s
