adjust-cell-width = -10%
font-family = IoskeleyMono Nerd Font Medium
font-family-bold = IoskeleyMono Nerd Font
font-family-bold-italic = IoskeleyMono Nerd Font
font-family-italic = IoskeleyMono Nerd Font Medium
font-size = 13.5

font-family = Symbols Nerd Font

# vim: commentstring=#\ %s
