adjust-cell-width = -10%
font-family = Ioskeley Mono
font-family-bold = Ioskeley Mono
font-family-bold-italic = Ioskeley Mono
font-family-italic = Ioskeley Mono
font-family = Symbols Nerd Font
font-size = 13.5

# vim: commentstring=#\ %s
