adjust-cell-width = -10%
font-family = Maple Mono NF
font-family-bold = Maple Mono NF
font-family-italic = Maple Mono NF
font-family-bold-italic = Maple Mono NF
font-family = Symbols Nerd Font
font-size = 13.5

# vim: commentstring=#\ %s
