adjust-cell-width = -15%
font-family = Noto Sans Mono ExtraCondensed
font-family-bold = Noto Sans Mono ExtraCondensed
font-family-bold-italic = Maple Mono NF
font-family-italic = Maple Mono NF
font-family = Symbols Nerd Font
font-size = 14.5

# vim: commentstring=#\ %s
